version: 2.1

orbs:
    lambda-tunnel: lambdatest/lambda-tunnel@volatile

workflows:      
    basic_workflow:
        jobs:
          - lambda-tunnel/with_tunnel:
              name: "Chrome test"
              tunnel_name: "chrome"
              lambdatest_email: "vishnukdas"
              steps:
                - run: 
                    command: |
                      -npm install
                      -export LT_ACCESS_KEY="40fkQ3JuRlYMzd4ff7uqkqXCTnwvvkEB7FWJz1sLS2qSqoEDal"
                      -export LT_USERNAME="vishnukdas"
                      -node_modules/.bin/nightwatch -e chrome